version: '3'
services:
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  db-orders:
    container_name: db-orders
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: -p 3000

  db-providers:
    container_name: db-providers
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_providers
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "3100:3100"
    expose:
      - 3100
    command: -p 3100